---
title: "Lineage Metrics Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
library(reshape2)
library(dplyr)
library(scales)
```


```{r, echo=FALSE}
alex_real_value_data <- read_csv("alex_real_value_data.csv")
emily_real_value_data <- read_csv("real_value_data.csv")
real_value_data <- merge(alex_real_value_data, emily_real_value_data, all = TRUE)
real_value_data$problem <- sapply(as.character(real_value_data$p),switch,"0"="Himmelblau","1"="Six-hump camel back","2"="Shubert", "6"="Composition function 2")
real_value_data$problem <- as.factor(real_value_data$problem)
real_value_data$selection <- sapply(as.character(real_value_data$selection),switch,"0"="Tournament","1"="Lexicase","2"="Eco-EA", "3"="MAP-Elites", "4"="Roulette", "5"="Drift")
real_value_data$selection <- as.factor(real_value_data$selection)
real_value_data$seed <- as.factor(real_value_data$seed)
#real_value_data$ts <- as.factor(real_value_data$ts)
real_value_data$elite <- as.factor(real_value_data$elite)
#real_value_data$mutation_rate <- as.factor(real_value_data$mutation_rate)
tournament_data <- subset(real_value_data, real_value_data$selection == "Tournament" & real_value_data$elite == 0)
melted_tournament_data <- melt(tournament_data, id.vars = c("update", "selection", "seed", "elite", "mutation_rate", "le", "p", "problem", "g", "ts"))
end_points_vars_of_interest <- melted_tournament_data %>% filter(update==5000) %>% filter(variable %in% c("mrca_depth", "dominant_deleterious_steps", "mean_evolutionary_distinctiveness", "variance_evolutionary_distinctiveness", "current_phylogenetic_diversity", "mean_pairwise_distance", "variance_pairwise_distance", "ave_depth"))

labels <- c(current_phylogenetic_diversity = "Phylogenetic diversity", dominant_deleterious_steps = "Dominant deleterious steps", mean_evolutionary_distinctiveness="Mean evo. distinctiveness", mean_pairwise_distance="Mean pairwise distance", mrca_depth="MRCA depth", variance_evolutionary_distinctiveness="Variance evo. distinctiveness", variance_pairwise_distance = "Variance pairwise distance")


```

```{r}
ggplot(subset(end_points_vars_of_interest, end_points_vars_of_interest$mutation_rate==.001), aes(x=ts, y=value, color=problem)) + stat_summary(fun.y = median, fun.ymin = function(x){quantile(x)[2]}, fun.ymax=function(x){quantile(x)[4]}) +stat_summary(geom="line", fun.y=median)+ theme_classic() + scale_x_log10("Tournament size", breaks=c(2,4,8,16)) + scale_y_continuous("", labels=comma) + facet_wrap(~variable, scales="free_y", labeller = labeller(variable=labels)) + scale_color_discrete("Problem") + theme(legend.position = "bottom")
ggsave("../figs/all_ts.png", width=7, height=5) 
```


```{r}
ggplot(subset(end_points_vars_of_interest, end_points_vars_of_interest$ts==4), aes(x=mutation_rate, y=value, color=problem)) + stat_summary(fun.y = median, fun.ymin = function(x){quantile(x)[2]}, fun.ymax=function(x){quantile(x)[4]}) +stat_summary(geom="line", fun.y=median)+ theme_classic() + scale_x_log10("Mutation rate", labels=scientific) + scale_y_continuous("", labels=comma) + facet_wrap(~variable, scales="free_y", labeller = labeller(variable=labels)) +scale_color_discrete("Problem") +theme(legend.position = "bottom")
ggsave("../figs/all_mutation_rate.png", width=7, height=5)

```